<?php
/**
 * Forks a lagoon — clones the post, its files, and its lineage meta.
 *
 * @package Gin0115\Codelagoon\Features\Fork
 */

declare(strict_types=1);

namespace Gin0115\Codelagoon\Features\Fork;

use Gin0115\Codelagoon\Features\Database\FileRepository;
use Gin0115\Codelagoon\Features\Meta\LagoonMeta;
use Gin0115\Codelagoon\Features\PostType\LagoonPostType;
use WP_Error;
use WP_Post;
use WP_User;

defined( 'ABSPATH' ) || exit;

/**
 * Service that creates a fork of an existing lagoon.
 *
 * Forking copies:
 *  - The lagoon post (title, excerpt, content) into a new draft owned by the
 *    forking user. The slug is auto-generated by `SlugGenerator` on insert.
 *  - All file rows in `wp_codelag_lagoon_files`, via FileRepository::clone_files.
 *
 * Lineage is recorded via three post meta keys on the new lagoon:
 *  - `_lagoon_forked_from`  : immediate parent ID (the source).
 *  - `_lagoon_fork_root`    : top-of-chain ancestor — the original lagoon at
 *                              the start of this fork tree. If the source has
 *                              its own root, the new fork shares it; otherwise
 *                              the source itself becomes the root.
 *  - `_lagoon_fork_history` : ordered list of ancestor records (most-recent
 *                              first). On every fork the source's snapshot is
 *                              prepended onto the source's existing history,
 *                              then truncated to MAX_HISTORY entries.
 *
 * Snapshots are frozen at fork time so the chain survives later deletion of
 * intermediate lagoons or the original users.
 */
final class ForkService {

	/**
	 * Maximum number of ancestor records kept on `_lagoon_fork_history`.
	 *
	 * Long enough to be useful, short enough to keep meta read/write cheap.
	 */
	public const MAX_HISTORY = 50;

	/**
	 * Shared file repository (owns the files custom table).
	 */
	private FileRepository $files;

	public function __construct( FileRepository $files ) {
		$this->files = $files;
	}

	/**
	 * Create a fork of `$source_id` owned by `$user_id`.
	 *
	 * @param int $source_id Lagoon being forked.
	 * @param int $user_id   New owner (typically the current logged-in user).
	 * @return int|WP_Error  ID of the new lagoon, or WP_Error on failure.
	 */
	public function fork( int $source_id, int $user_id ) {
		$source = get_post( $source_id );
		if ( ! $source instanceof WP_Post || LagoonPostType::POST_TYPE !== $source->post_type ) {
			return new WP_Error(
				'codelag_fork_source_not_found',
				__( 'Cannot fork: source lagoon not found.', 'codelag-features' ),
				array( 'status' => 404 )
			);
		}

		if ( $user_id <= 0 ) {
			return new WP_Error(
				'codelag_fork_invalid_user',
				__( 'Cannot fork: invalid user.', 'codelag-features' ),
				array( 'status' => 400 )
			);
		}

		// Resolve the chain root. If the source already has a root recorded,
		// the new fork inherits it; otherwise the source itself is the root.
		$source_root = (int) get_post_meta( $source_id, LagoonMeta::META_FORK_ROOT, true );
		$root_id     = $source_root > 0 ? $source_root : $source_id;

		// Build the new history list: prepend a snapshot of the source onto
		// the source's existing history, then cap at MAX_HISTORY entries.
		$source_history = get_post_meta( $source_id, LagoonMeta::META_FORK_HISTORY, true );
		if ( ! is_array( $source_history ) ) {
			$source_history = array();
		}

		$source_user   = get_userdata( (int) $source->post_author );
		$source_record = array(
			'id'        => (int) $source->ID,
			'user'      => (int) $source->post_author,
			'username'  => $source_user instanceof WP_User ? $source_user->user_login : '',
			'forked_at' => current_time( 'mysql', true ),
		);

		$history = array_merge( array( $source_record ), $source_history );
		if ( count( $history ) > self::MAX_HISTORY ) {
			$history = array_slice( $history, 0, self::MAX_HISTORY );
		}

		// Insert the new post. SlugGenerator's wp_insert_post_data filter will
		// stamp a fresh random slug on it because the new ID has no auto-draft
		// history (the post is born straight as `draft`).
		$new_id = wp_insert_post(
			array(
				'post_type'    => LagoonPostType::POST_TYPE,
				'post_status'  => 'draft',
				'post_author'  => $user_id,
				'post_title'   => $source->post_title,
				'post_excerpt' => $source->post_excerpt,
				'post_content' => $source->post_content,
			),
			true
		);

		if ( is_wp_error( $new_id ) ) {
			return $new_id;
		}
		if ( ! is_int( $new_id ) || $new_id <= 0 ) {
			return new WP_Error(
				'codelag_fork_insert_failed',
				__( 'Failed to create forked lagoon post.', 'codelag-features' ),
				array( 'status' => 500 )
			);
		}

		// Stamp lineage meta before cloning files so any meta-driven
		// denormalisation hooks see the right values during the file insert.
		update_post_meta( $new_id, LagoonMeta::META_FORKED_FROM, $source_id );
		update_post_meta( $new_id, LagoonMeta::META_FORK_ROOT, $root_id );
		update_post_meta( $new_id, LagoonMeta::META_FORK_HISTORY, $history );

		// Clone every file row from the source into the new lagoon. Owner
		// and visibility columns are filled from the new post inside
		// FileRepository::clone_files (denormalised on insert).
		$this->files->clone_files( $source_id, $new_id );

		// Inherit taxonomy assignments from the source. Without this the new
		// lagoon has no language / tags / purpose, so it disappears from
		// every archive filter until the forker re-enters them manually.
		$this->copy_terms( $source_id, $new_id );

		return $new_id;
	}

	/**
	 * Copy every taxonomy term from one lagoon to another by term ID. Uses
	 * all taxonomies currently registered against the lagoon CPT so new
	 * taxonomies added later are picked up automatically.
	 */
	private function copy_terms( int $source_id, int $target_id ): void {
		$taxonomies = get_object_taxonomies( LagoonPostType::POST_TYPE );
		foreach ( $taxonomies as $taxonomy ) {
			$terms = wp_get_object_terms( $source_id, $taxonomy, array( 'fields' => 'ids' ) );
			if ( is_wp_error( $terms ) || array() === $terms ) {
				continue;
			}
			wp_set_object_terms( $target_id, array_map( 'intval', $terms ), $taxonomy, false );
		}
	}
}
